#!/usr/bin/env python

import rospy
from sr_robot_commander.sr_arm_commander import SrArmCommander

rospy.init_node("calibration_trajectory", anonymous=True)

arm_commander = SrArmCommander(set_ground=False)

rospy.sleep(rospy.Duration(2))

trajectory = [
                {
                    "name": "calibration_above_arm",
                    "interpolate_time": 4.0,
                    "pause_time": 1.0
                },
                {
                    "name": "calibration_in_place_arm",
                    "interpolate_time": 4.0,
                    "pause_time": 1.0
                },
            ]

arm_commander.run_named_trajectory(trajectory)
